### ISSUE TITLE
Fullscreen Capture interrupted by UAC prompt

### ISSUE THREAD

**Issue by vkedwardli** [leadedge/SpoutCapture#4]
Hi it's me again, sorry for providing false information last time

I think the paused fullscreen capture is caused by the Windows User Account Control prompt
<img width="534" alt="Screenshot 2021-11-03 at 2 48 54 PM" src="https://user-images.githubusercontent.com/602245/140036448-907537ae-ab84-4506-9f9a-8205da42f2ed.png">

Reproducible by running cmd with admin rights

**Comment by leadedge** [comment]
Thanks for letting me know. If it's a new machine this sort of thing would be expected.  I will try to reproduce to see if there is anything that can be done. The only thing out of the ordinary is use of a "mouse hook" to detect a mouse click outside the application window.

You might also like to try ["Win32CaptureSample"](https://github.com/leadedge/Win32CaptureSample) which uses a different capture method altogether and a "picker" to select the required window. It is a modification of a sample from a developer on the Microsoft Windows Composition team and should give much better speed for window capture. It also allows full screen capture of different displays.

You need to download all three files [here](https://github.com/leadedge/Win32CaptureSample/tree/master/Spout/Binaries).

**Comment by leadedge** [comment]
I mis-understood at first that SpoutCapture was causing the UAC prompt. But it seems that access to the desktop is prevented while the UAC prompt is active. I confirmed that after the UAC prompt has been dismissed, SpoutCapture full screen or region capture is frozen.

OBS users have reported the [same problem](https://obsproject.com/forum/threads/screen-turns-black-after.108940/#post-413813). The suggested solution works OK but it prevents the UAC prompt from appearing at all and the reduced security level might not be what you want.

I will see if there is a workaround for SpoutCapture, but the Win32CaptureSample screen capture is not frozen by the UAC prompt, so that's probably a better solution.

**Comment by leadedge** [comment]
Release v2.001 detects loss of access and attempts re-connection. Testing shows that this happens as soon as the UAC prompt is removed and the normal desktop is resumed. Lowering security also resolves the problem, but this should work if that is not acceptable.

**Comment by vkedwardli** [comment]
Thanks a lot, capture no longer pause now!

**Comment by leadedge** [comment]
OK that should work. I will investigate "Win32CaptureSample" a little more.
